// RavonPay Landing — 3 tilli tarjimalar (uz/en/ru)
export const LANDING_I18N = {
  uz: {
    'nav.features': 'Imkoniyatlar', 'nav.how': 'Qanday ishlaydi', 'nav.who': 'Kim uchun', 'nav.pricing': 'Narxlar', 'nav.cta': 'Boshlash',
    'hero.badge': 'Markaziy Osiyo uchun fintech', 'hero.title': 'Pulni <span class="gradient-text">chegarasiz</span> harakatlantiring', 'hero.sub': 'Yuboring, qabul qiling va biznesingizni boshqaring — bitta zamonaviy hamyonda. Frilanserlar, sotuvchilar va bizneslar uchun yaratilgan.', 'hero.cta1': 'Bepul boshlash', 'hero.cta2': 'Qanday ishlaydi', 'hero.t1': "Bepul ro'yxatdan o'tish", 'hero.t2': 'Bank darajasidagi xavfsizlik',
    'hero.cardLabel': 'Umumiy balans', 'hero.r1n': "Upwork to'lovi", 'hero.r1t': 'Bugun, 14:32', 'hero.r2n': 'Aziz K. ga', 'hero.r2t': 'Kecha, 09:15', 'hero.badgeIn': "+2 500 000 so'm", 'hero.badgePaid': "To'lov qabul qilindi",
    'logos.label': 'ULAR BILAN INTEGRATSIYA — TEZ ORADA',
    'feat.eyebrow': 'Imkoniyatlar', 'feat.title': 'Bitta platformada hamma narsa', 'feat.sub': "Shaxsiy hamyondan tortib biznes to'lovlarigacha — RavonPay siz uchun ishlaydi.",
    'feat.f1t': "Tezkor to'lovlar", 'feat.f1d': 'Bir necha soniyada pul yuboring va qabul qiling. Telefon raqami yoki QR kod orqali.', 'feat.f2t': "To'lov havolalari", 'feat.f2d': "Bir bosishda to'lov havolasi yarating. Mijozlaringizga yuboring va pulni oling.", 'feat.f3t': "Xalqaro to'lovlar", 'feat.f3d': "Dunyoning istalgan nuqtasidan to'lov qabul qiling. Frilanserlar uchun ideal.", 'feat.f4t': 'Biznes analitika', 'feat.f4d': 'Daromadingizni real vaqtda kuzating. Hisobotlar va statistika bir joyda.', 'feat.f5t': 'Virtual kartalar', 'feat.f5d': "Onlayn to'lovlar uchun virtual karta oching. Xavfsiz va tezkor.", 'feat.f6t': 'Bank xavfsizligi', 'feat.f6d': '2FA, shifrlash va firibgarlikka qarshi himoya. Pulingiz har doim xavfsiz.',
    'how.eyebrow': 'Oddiy jarayon', 'how.title': '3 qadamda boshlang', 'how.sub': "Ro'yxatdan o'tishdan birinchi to'lovgacha — bir necha daqiqa.",
    'how.s1t': "Ro'yxatdan o'ting", 'how.s1d': 'Telefon raqami va email bilan akkaunt yarating. Tez va bepul.', 'how.s2t': "Hamyonni to'ldiring", 'how.s2d': "Karta yoki bank o'tkazmasi orqali balansni to'ldiring.", 'how.s3t': "To'lashni boshlang", 'how.s3d': "Pul yuboring, qabul qiling yoki to'lov havolasi yarating.",
    'aud.eyebrow': 'Kim uchun', 'aud.title': 'Har kim uchun yaratilgan', 'aud.c1tag': 'Biznes', 'aud.c1t': 'Bizneslar va sotuvchilar', 'aud.c1d': "To'lovlarni qabul qiling, mijozlarni boshqaring va biznesingizni o'stiring.", 'aud.c1l1': "To'lov havolalari va checkout sahifalari", 'aud.c1l2': "Jamoa a'zolari va rollar", 'aud.c1l3': 'Hisob-fakturalar va analitika', 'aud.c2tag': 'Shaxsiy', 'aud.c2t': 'Frilanser va shaxslar', 'aud.c2d': "Xalqaro to'lovlarni oling, do'stlarga pul yuboring, xarajatlarni kuzating.", 'aud.c2l1': "Tezkor P2P o'tkazmalar", 'aud.c2l2': "Xalqaro to'lovlarni qabul qilish", 'aud.c2l3': 'Virtual kartalar va analitika',
    'cta.title': "Bugun RavonPay'ni boshlang", 'cta.sub': "Bir necha daqiqada ro'yxatdan o'ting. Kredit karta talab qilinmaydi.", 'cta.btn': 'Bepul akkaunt yaratish',
    'foot.tag': 'Markaziy Osiyo uchun zamonaviy fintech platforma. Pulni chegarasiz harakatlantiring.', 'foot.product': 'Mahsulot', 'foot.api': 'API', 'foot.security': 'Xavfsizlik', 'foot.company': 'Kompaniya', 'foot.about': 'Biz haqimizda', 'foot.blog': 'Blog', 'foot.careers': 'Karyera', 'foot.contact': 'Aloqa', 'foot.legal': 'Huquqiy', 'foot.privacy': 'Maxfiylik', 'foot.terms': 'Shartlar', 'foot.compliance': 'Muvofiqlik', 'foot.rights': 'Barcha huquqlar himoyalangan.'
  },
  en: {
    'nav.features': 'Features', 'nav.how': 'How it works', 'nav.who': "Who it's for", 'nav.pricing': 'Pricing', 'nav.cta': 'Get started',
    'hero.badge': 'Fintech for Central Asia', 'hero.title': 'Move money <span class="gradient-text">without limits</span>', 'hero.sub': 'Send, receive and run your business — in one modern wallet. Built for freelancers, sellers and businesses.', 'hero.cta1': 'Start free', 'hero.cta2': 'How it works', 'hero.t1': 'Free sign up', 'hero.t2': 'Bank-grade security',
    'hero.cardLabel': 'Total balance', 'hero.r1n': 'Upwork payment', 'hero.r1t': 'Today, 14:32', 'hero.r2n': 'To Aziz K.', 'hero.r2t': 'Yesterday, 09:15', 'hero.badgeIn': '+2,500,000 UZS', 'hero.badgePaid': 'Payment received',
    'logos.label': 'INTEGRATIONS — COMING SOON',
    'feat.eyebrow': 'Features', 'feat.title': 'Everything on one platform', 'feat.sub': 'From a personal wallet to business payments — RavonPay works for you.',
    'feat.f1t': 'Instant payments', 'feat.f1d': 'Send and receive money in seconds. Via phone number or QR code.', 'feat.f2t': 'Payment links', 'feat.f2d': 'Create a payment link in one click. Send to customers and get paid.', 'feat.f3t': 'Global payments', 'feat.f3d': 'Accept payments from anywhere in the world. Ideal for freelancers.', 'feat.f4t': 'Business analytics', 'feat.f4d': 'Track your revenue in real time. Reports and stats in one place.', 'feat.f5t': 'Virtual cards', 'feat.f5d': 'Open a virtual card for online payments. Secure and fast.', 'feat.f6t': 'Bank security', 'feat.f6d': '2FA, encryption and fraud protection. Your money is always safe.',
    'how.eyebrow': 'Simple process', 'how.title': 'Start in 3 steps', 'how.sub': 'From sign up to first payment — just a few minutes.',
    'how.s1t': 'Sign up', 'how.s1d': 'Create an account with your phone and email. Fast and free.', 'how.s2t': 'Top up your wallet', 'how.s2d': 'Add funds via card or bank transfer.', 'how.s3t': 'Start paying', 'how.s3d': 'Send, receive or create a payment link.',
    'aud.eyebrow': "Who it's for", 'aud.title': 'Built for everyone', 'aud.c1tag': 'Business', 'aud.c1t': 'Businesses & sellers', 'aud.c1d': 'Accept payments, manage customers and grow your business.', 'aud.c1l1': 'Payment links and checkout pages', 'aud.c1l2': 'Team members and roles', 'aud.c1l3': 'Invoices and analytics', 'aud.c2tag': 'Personal', 'aud.c2t': 'Freelancers & individuals', 'aud.c2d': 'Receive international payments, send money to friends, track expenses.', 'aud.c2l1': 'Instant P2P transfers', 'aud.c2l2': 'Accept international payments', 'aud.c2l3': 'Virtual cards and analytics',
    'cta.title': 'Get started with RavonPay today', 'cta.sub': 'Sign up in minutes. No credit card required.', 'cta.btn': 'Create a free account',
    'foot.tag': 'A modern fintech platform for Central Asia. Move money without limits.', 'foot.product': 'Product', 'foot.api': 'API', 'foot.security': 'Security', 'foot.company': 'Company', 'foot.about': 'About us', 'foot.blog': 'Blog', 'foot.careers': 'Careers', 'foot.contact': 'Contact', 'foot.legal': 'Legal', 'foot.privacy': 'Privacy', 'foot.terms': 'Terms', 'foot.compliance': 'Compliance', 'foot.rights': 'All rights reserved.'
  },
  ru: {
    'nav.features': 'Возможности', 'nav.how': 'Как это работает', 'nav.who': 'Для кого', 'nav.pricing': 'Цены', 'nav.cta': 'Начать',
    'hero.badge': 'Финтех для Центральной Азии', 'hero.title': 'Перемещайте деньги <span class="gradient-text">без границ</span>', 'hero.sub': 'Отправляйте, получайте и управляйте бизнесом — в одном современном кошельке. Создан для фрилансеров, продавцов и бизнеса.', 'hero.cta1': 'Начать бесплатно', 'hero.cta2': 'Как это работает', 'hero.t1': 'Бесплатная регистрация', 'hero.t2': 'Банковская безопасность',
    'hero.cardLabel': 'Общий баланс', 'hero.r1n': 'Оплата Upwork', 'hero.r1t': 'Сегодня, 14:32', 'hero.r2n': 'Азизу К.', 'hero.r2t': 'Вчера, 09:15', 'hero.badgeIn': '+2 500 000 сум', 'hero.badgePaid': 'Платёж получен',
    'logos.label': 'ИНТЕГРАЦИИ — СКОРО',
    'feat.eyebrow': 'Возможности', 'feat.title': 'Всё на одной платформе', 'feat.sub': 'От личного кошелька до бизнес-платежей — RavonPay работает для вас.',
    'feat.f1t': 'Мгновенные платежи', 'feat.f1d': 'Отправляйте и получайте деньги за секунды. По номеру телефона или QR-коду.', 'feat.f2t': 'Платёжные ссылки', 'feat.f2d': 'Создайте платёжную ссылку в один клик. Отправьте клиентам и получите оплату.', 'feat.f3t': 'Международные платежи', 'feat.f3d': 'Принимайте платежи из любой точки мира. Идеально для фрилансеров.', 'feat.f4t': 'Бизнес-аналитика', 'feat.f4d': 'Отслеживайте доход в реальном времени. Отчёты и статистика в одном месте.', 'feat.f5t': 'Виртуальные карты', 'feat.f5d': 'Откройте виртуальную карту для онлайн-платежей. Безопасно и быстро.', 'feat.f6t': 'Банковская защита', 'feat.f6d': '2FA, шифрование и защита от мошенничества. Ваши деньги всегда в безопасности.',
    'how.eyebrow': 'Простой процесс', 'how.title': 'Начните за 3 шага', 'how.sub': 'От регистрации до первого платежа — всего несколько минут.',
    'how.s1t': 'Зарегистрируйтесь', 'how.s1d': 'Создайте аккаунт с телефоном и email. Быстро и бесплатно.', 'how.s2t': 'Пополните кошелёк', 'how.s2d': 'Добавьте средства картой или банковским переводом.', 'how.s3t': 'Начните платить', 'how.s3d': 'Отправляйте, получайте или создавайте платёжные ссылки.',
    'aud.eyebrow': 'Для кого', 'aud.title': 'Создан для каждого', 'aud.c1tag': 'Бизнес', 'aud.c1t': 'Бизнес и продавцы', 'aud.c1d': 'Принимайте платежи, управляйте клиентами и развивайте бизнес.', 'aud.c1l1': 'Платёжные ссылки и страницы оплаты', 'aud.c1l2': 'Участники команды и роли', 'aud.c1l3': 'Счета и аналитика', 'aud.c2tag': 'Личный', 'aud.c2t': 'Фрилансеры и частные лица', 'aud.c2d': 'Получайте международные платежи, отправляйте деньги друзьям, отслеживайте расходы.', 'aud.c2l1': 'Мгновенные P2P-переводы', 'aud.c2l2': 'Приём международных платежей', 'aud.c2l3': 'Виртуальные карты и аналитика',
    'cta.title': 'Начните с RavonPay сегодня', 'cta.sub': 'Регистрация за минуты. Кредитная карта не требуется.', 'cta.btn': 'Создать бесплатный аккаунт',
    'foot.tag': 'Современная финтех-платформа для Центральной Азии. Перемещайте деньги без границ.', 'foot.product': 'Продукт', 'foot.api': 'API', 'foot.security': 'Безопасность', 'foot.company': 'Компания', 'foot.about': 'О нас', 'foot.blog': 'Блог', 'foot.careers': 'Карьера', 'foot.contact': 'Контакты', 'foot.legal': 'Правовое', 'foot.privacy': 'Конфиденциальность', 'foot.terms': 'Условия', 'foot.compliance': 'Соответствие', 'foot.rights': 'Все права защищены.'
  }
};
